environment:
  LOG_DESTINATIONS: ${LOG_DESTINATIONS}
packages:
  - name: mokapos
    actions:
      - name: client_abc
        runtime: 'nodejs:18'
  - name: mokapos
    actions:
      - name: client_def
        runtime: 'nodejs:18'
  - name: shopify
    actions:
      - name: client_ghi
        runtime: 'nodejs:18'
